default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: Admin12345!
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_development


